name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          repository: openstack/glance
          ref: 9e4b13797baf87bbf4871a253277f977bd755ce3 # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/checkout@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          repository: openstack/glance_store
          ref: f1a1124e4f6788af1044370898c08b569819dd3a # stable/2025.2

      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@9dc904e06dcde958bf8a0b3230715d32b9e3a85f # main
        with:
          image-name: glance
          build-contexts: |
            glance=openstack/glance
            glance_store=openstack/glance_store
          push: ${{ github.event_name != 'pull_request' }}
